# Generated by Django 3.2 on 2022-02-21 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, verbose_name='Структурное подразделение')),
            ],
            options={
                'verbose_name': 'Структурное подразделение',
                'verbose_name_plural': 'Структурные подразделения',
            },
        ),
        migrations.CreateModel(
            name='DepartmentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('windows_name', models.CharField(blank=True, max_length=100, verbose_name='Логин домена')),
                ('proxy_name', models.CharField(max_length=100, verbose_name='Логин прокси')),
                ('post_name', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proxy.department')),
            ],
            options={
                'verbose_name': 'Пользователь интернета',
                'verbose_name_plural': 'Пользователи интернета',
            },
        ),
    ]
