# Generated by Django 3.2 on 2021-12-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsVKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_data', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_organizer', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=200)),
                ('event_place', models.CharField(max_length=200)),
                ('event_document', models.CharField(blank=True, max_length=200)),
                ('event_description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['event_data', 'event_time'],
            },
        ),
    ]
