# Generated by Django 3.2 on 2022-02-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsvks',
            options={'ordering': ['event_data', 'event_time'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_data',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_document',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_organizer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='eventsvks',
            name='event_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Тип'),
        ),
    ]
